server:
  port: 0

spring:
  application:
    name: remit-service

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    intelligent_bank_msa: DEBUG

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info